'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, ChevronDown, Heart, Menu, Search, ShoppingBag, X } from 'lucide-react'
import { products, featuredProducts } from '@/data/products'
import type { CartItem, Product } from '@/types/product'

export function Navbar() {
  const [open, setOpen] = useState(false)
  const [search, setSearch] = useState(false)
  return <>
    <header className="nav"><Link href="/" className="wordmark">ZENJI<span className="dot">.</span></Link><nav className="desktop-nav"><Link href="/shop">Shop</Link><Link href="/collections">Collections</Link><Link href="/about">About</Link></nav><div className="nav-actions"><button aria-label="Search" onClick={() => setSearch(true)}><Search size={18}/></button><Link href="/cart" aria-label="Cart"><ShoppingBag size={18}/></Link><button className="menu-button" aria-label="Open menu" onClick={() => setOpen(true)}><Menu size={20}/></button></div></header>
    {open && <div className="mobile-menu"><button className="close" onClick={() => setOpen(false)} aria-label="Close menu"><X/></button><span className="kicker">ZENJI TOKYO / 2026</span><nav><Link onClick={() => setOpen(false)} href="/shop">Shop <ArrowUpRight/></Link><Link onClick={() => setOpen(false)} href="/collections">Collections <ArrowUpRight/></Link><Link onClick={() => setOpen(false)} href="/about">About <ArrowUpRight/></Link></nav><div className="mobile-social">Instagram / TikTok / X</div></div>}
    {search && <SearchOverlay close={() => setSearch(false)}/>}</>
}

function SearchOverlay({ close }: { close: () => void }) { const [q,setQ] = useState(''); const matches = products.filter(p => `${p.name} ${p.category} ${p.collection}`.toLowerCase().includes(q.toLowerCase())).slice(0,5); return <div className="search-overlay" role="dialog" aria-modal="true"><button className="close" onClick={close} aria-label="Close search"><X/></button><span className="kicker">SEARCH ZENJI</span><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="What are you looking for?"/><div className="search-results">{q && matches.map(p=><Link onClick={close} href={`/shop/${p.slug}`} key={p.id}><span>{p.name}</span><span>${p.price}</span></Link>)}{q && !matches.length && <p className="muted">NO MATCHES FOUND. TRY ANOTHER SEARCH.</p>}</div></div> }

export function ProductCard({ product }: { product: Product }) { const [wish,setWish]=useState(false); return <article className="product-card"><Link href={`/shop/${product.slug}`} className="product-image"><Image src={product.images[0]} alt={product.name} fill sizes="(max-width: 700px) 50vw, 25vw"/><Image className="second-image" src={product.images[1]} alt="" fill sizes="(max-width: 700px) 50vw, 25vw"/>{product.isNew && <span className="badge">New</span>}</Link><button className={`wishlist ${wish?'active':''}`} onClick={()=>setWish(!wish)} aria-label={`${wish?'Remove':'Add'} ${product.name} from wishlist`}><Heart size={17} fill={wish?'currentColor':'none'}/></button><div className="product-meta"><Link href={`/shop/${product.slug}`}><h3>{product.name}</h3></Link><span>{product.category}</span><strong>${product.price}</strong></div><button className="quick-add" onClick={()=>window.dispatchEvent(new CustomEvent('zenji:add',{detail:{product,size:product.sizes[0],color:product.colors[0]}}))}>Quick add <ArrowUpRight size={15}/></button></article> }

export function ProductGrid({ items = products }: { items?: Product[] }) { return <div className="product-grid">{items.map(p=><ProductCard key={p.id} product={p}/>)}</div> }

export function Newsletter() { const [email,setEmail]=useState(''); const [done,setDone]=useState(false); const submit=(e:React.FormEvent)=>{e.preventDefault(); if(email.includes('@')) setDone(true)}; return <section className="newsletter"><span className="kicker">STAY IN THE LOOP</span>{done?<h2>YOU&apos;RE IN.<br/>WATCH YOUR INBOX.</h2>:<><h2>NEW DROPS.<br/><em>NO NOISE.</em></h2><form onSubmit={submit}><label className="sr-only" htmlFor="email">Email address</label><input id="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="ENTER YOUR EMAIL"/><button>Join Zenji <ArrowUpRight size={17}/></button></form></>}</section> }

export function Footer() { return <footer><div className="footer-top"><Link href="/" className="wordmark">ZENJI<span className="dot">.</span></Link><p>ANIME ROOTS.<br/>STREET CULTURE.<br/>BUILT DIFFERENT.</p></div><div className="footer-links"><div><span className="kicker">Explore</span><Link href="/shop">Shop</Link><Link href="/collections">Collections</Link><Link href="/about">About</Link></div><div><span className="kicker">Customer</span><a href="#">Shipping</a><a href="#">Returns</a><a href="#">Size guide</a></div><div><span className="kicker">Follow</span><a href="#">Instagram</a><a href="#">TikTok</a><a href="#">X / Twitter</a></div></div><div className="footer-bottom">© 2026 ZENJI. ALL RIGHTS RESERVED.<span>PRIVACY &nbsp; TERMS</span></div></footer> }

export function CartProvider({ children }: { children: React.ReactNode }) { const [items,setItems]=useState<CartItem[]>([]); useEffect(()=>{const raw=localStorage.getItem('zenji-cart'); if(raw) setItems(JSON.parse(raw)); const fn=(e:Event)=>{const d=(e as CustomEvent).detail as CartItem; setItems(old=>{const found=old.find(i=>i.product.id===d.product.id&&i.size===d.size); const next=found?old.map(i=>i===found?{...i,quantity:i.quantity+1}:i):[...old,{...d,quantity:1}]; localStorage.setItem('zenji-cart',JSON.stringify(next)); return next})}; window.addEventListener('zenji:add',fn); return()=>window.removeEventListener('zenji:add',fn)},[]); return <CartContext.Provider value={{items,setItems}}>{children}</CartContext.Provider> }
import { createContext, useContext } from 'react'
const CartContext=createContext<{items:CartItem[];setItems:React.Dispatch<React.SetStateAction<CartItem[]>>}|null>(null)
export function useCart(){const c=useContext(CartContext); if(!c) throw new Error('useCart must be inside CartProvider'); return c}
export function CartCount(){const {items}=useCart(); return <>{items.reduce((a,i)=>a+i.quantity,0)>0 && <span className="cart-count">{items.reduce((a,i)=>a+i.quantity,0)}</span>}</>}

export function Marquee(){return <div className="marquee"><div>ZENJI — DROP 001 — STREET CULTURE — ANIME ROOTS — ZENJI — DROP 001 — STREET CULTURE — ANIME ROOTS — </div></div>}
export function Hero(){return <section className="hero"><Image src="/images/zenji-hero.png" alt="Model wearing ZENJI streetwear in Tokyo" fill priority sizes="100vw"/><div className="hero-shade"/><div className="hero-copy"><span className="kicker">DROP 001 SS / 26 &nbsp; TOKYO → WORLD</span><h1>WEAR<br/><em>THE UNSEEN.</em></h1><p>ANIME ROOTS. STREET CULTURE.<br/>BUILT DIFFERENT.</p><Link className="button button-light" href="/shop">Shop the drop <ArrowUpRight size={18}/></Link></div><span className="hero-vertical">ZENJI / 001</span></section>}
export function CartSummary(){const {items,setItems}=useCart(); const total=items.reduce((a,i)=>a+i.product.price*i.quantity,0); const change=(item:CartItem,n:number)=>setItems(old=>{const next=n<1?old.filter(i=>i!==item):old.map(i=>i===item?{...i,quantity:n}:i);localStorage.setItem('zenji-cart',JSON.stringify(next));return next}); return <>{items.map(i=><div className="cart-row" key={i.product.id+i.size}><Image src={i.product.images[0]} alt={i.product.name} width={100} height={120}/><div><Link href={`/shop/${i.product.slug}`}><h3>{i.product.name}</h3></Link><span>{i.size} / {i.color}</span><div className="qty"><button onClick={()=>change(i,i.quantity-1)} aria-label="Decrease quantity">−</button>{i.quantity}<button onClick={()=>change(i,i.quantity+1)} aria-label="Increase quantity">+</button></div></div><strong>${i.product.price*i.quantity}</strong></div>)}<div className="cart-total"><span>Subtotal</span><strong>${total}</strong></div></>}
export const useFeatured=()=>useMemo(()=>featuredProducts,[ ])
